spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost:3307/taskflowdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: taskflow
    password: taskflowpw
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration,filesystem:./flyway/sql
    baseline-on-migrate: true
    baseline-version: 0

api:
  security:
    token:
      secret: ${JWT_SECRET:123456}

server:
  port: 8080



    #admin: admin1234
    #manager1: manager1234
    #manager2: manager1234
    #collab1 até collab7: collab1234