services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskflowdb
      MYSQL_USER: taskflow
      MYSQL_PASSWORD: taskflowpw
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  mysql_data: